CREATE DATABASE IF NOT EXISTS hellas CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE hellas;

CREATE TABLE IF NOT EXISTS destinations (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  type VARCHAR(32) NOT NULL,
  slug VARCHAR(128) NOT NULL,
  name VARCHAR(255) NOT NULL,
  region VARCHAR(255) DEFAULT NULL,
  subtitle VARCHAR(255) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  image_path VARCHAR(500) DEFAULT NULL,
  detail_path VARCHAR(500) DEFAULT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_destination (type, slug),
  KEY idx_destination_type (type),
  KEY idx_destination_sort (sort_order)
);

INSERT IGNORE INTO destinations
  (type, slug, name, region, subtitle, description, image_path, detail_path, sort_order)
VALUES
  ('island', 'santorini', 'Santorini', 'Kykladen', 'Caldera und white cubes', 'Well known island with iconic sunsets and views of the caldera.', 'assets/img/islands/kyklades/santorini/santorinibild01.jpg', 'pages/islands/kyklades/santorini.html', 10),
  ('island', 'mykonos', 'Mykonos', 'Kykladen', 'Windmills and beach bars', 'Lively island with whitewashed lanes and long summer beach days.', 'assets/img/islands/kyklades/mykonos/mykonosbild01.jpg', 'pages/islands/kyklades/mykonos.html', 20),
  ('island', 'naxos', 'Naxos', 'Kykladen', 'Mountains, villages and long beaches', 'The largest Cycladic island mixes plateaus, tavernas and a long coastline.', 'assets/img/islands/kyklades/naxos/naxosbild01.jpg', 'pages/islands/kyklades/naxos.html', 30),
  ('island', 'paros', 'Paros', 'Kykladen', 'White towns and calm coves', 'An easygoing island with bright villages and many quiet beach stops.', 'assets/img/islands/kyklades/paros/parosbild01.jpg', 'pages/islands/kyklades/paros.html', 40),
  ('island', 'sifnos', 'Sifnos', 'Kykladen', 'Walking, pottery and good food', 'Known for village paths, terraces and a strong culinary tradition.', 'assets/img/islands/kyklades/sifnos/sifnosbild01.jpg', 'pages/islands/kyklades/sifnos.html', 50),
  ('island', 'milos', 'Milos', 'Kykladen', 'Volcanic coasts and colors', 'Famous for dramatic rock formations, coves and a very distinct landscape.', 'assets/img/islands/kyklades/milos/milosbild01.jpg', 'pages/islands/kyklades/milos.html', 60),
  ('island', 'siros', 'Siros', 'Kykladen', 'Island capital and neoclassic streets', 'Ermoupoli brings harbor life, city energy and historic facades together.', NULL, 'pages/islands/kyklades/siros.html', 70),
  ('island', 'tinos', 'Tinos', 'Kykladen', 'Village culture and wind', 'Tinos combines terraces, pilgrimage heritage, marble craft and small villages.', 'assets/img/islands/kyklades/tinos/tinosbild01.jpg', 'pages/islands/kyklades/tinos.html', 80),
  ('island', 'amorgos', 'Amorgos', 'Kykladen', 'Cliffs and deep blue water', 'Known for steep slopes, old paths and a striking sea horizon.', NULL, 'pages/islands/kyklades/amorgos.html', 90),
  ('island', 'anafi', 'Anafi', 'Kykladen', 'Quiet and open', 'A small island with space, simple routes and wide sea views.', NULL, 'pages/islands/kyklades/anafi.html', 100),
  ('island', 'andros', 'Andros', 'Kykladen', 'Green valleys and springs', 'Andros is more water-rich and green than many of its neighbors.', NULL, 'pages/islands/kyklades/andros.html', 110),
  ('island', 'folegandros', 'Folegandros', 'Kykladen', 'Compact and dramatic', 'A small island with steep cliffs, quiet lanes and a sharp silhouette.', NULL, 'pages/islands/kyklades/folegandros.html', 120),
  ('island', 'serifos', 'Serifos', 'Kykladen', 'Dusty paths and coves', 'Serifos blends island calm with rugged hills and open horizon lines.', NULL, 'pages/islands/kyklades/serifos.html', 130),
  ('island', 'iraklia', 'Iraklia', 'Kykladen', 'Small and remote', 'A quiet island for slow days, short walks and very little noise.', NULL, 'pages/islands/kyklades/iraklia.html', 140),
  ('island', 'antiparos', 'Antiparos', 'Kykladen', 'Small, friendly, relaxed', 'Known for easy evenings, a compact town and close-to-the-beach life.', NULL, 'pages/islands/kyklades/antiparos.html', 150),
  ('island', 'donoussa', 'Donoussa', 'Kykladen', 'Remote and still', 'Donoussa is all about quiet harbors, slow rhythm and minimal traffic.', NULL, 'pages/islands/kyklades/donoussa.html', 160),
  ('island', 'kea', 'Kea', 'Kykladen', 'Near Athens, calm in character', 'Kea offers hiking routes, stone villages and an easy weekend pace.', NULL, 'pages/islands/kyklades/kea.html', 170),
  ('island', 'kimolos', 'Kimolos', 'Kykladen', 'White earth and small coves', 'A small island with a gentle rhythm, light geology and few crowds.', NULL, 'pages/islands/kyklades/kimolos.html', 180),
  ('island', 'koufonisia', 'Koufonisia', 'Kykladen', 'Bright water and short distances', 'The small islands stand for clear water, beaches and very short walks.', NULL, 'pages/islands/kyklades/koufonisia.html', 190),
  ('island', 'kythnos', 'Kythnos', 'Kykladen', 'Thermal waters and coves', 'Kythnos combines beaches, villages and a grounded island rhythm.', NULL, 'pages/islands/kyklades/kythnos.html', 200),
  ('island', 'schinoussa', 'Schinoussa', 'Kykladen', 'Very small, very quiet', 'An island for walks, simple days and clear water.', NULL, 'pages/islands/kyklades/schinoussa.html', 210),
  ('island', 'sikinos', 'Sikinos', 'Kykladen', 'Unhurried and authentic', 'Sikinos stays quiet, simple and far from mass tourism.', NULL, 'pages/islands/kyklades/sikinos.html', 220),
  ('island', 'thirassia', 'Thirassia', 'Kykladen', 'Across from Santorini', 'The small neighbor of Santorini shows a quieter side of the region.', NULL, 'pages/islands/kyklades/thirassia.html', 230),
  ('island', 'ios', 'Ios', 'Kykladen', 'Young, bright, lively', 'Ios is known for beach days, summer nights and steep village lanes.', 'assets/img/islands/kyklades/ios/iosbild01.jpg', 'pages/islands/kyklades/ios.html', 240),
  ('island', 'korfu', 'Korfu', 'Ionische Inseln', 'Green hills and Venetian traces', 'Corfu combines old-town architecture, olive groves and a strong coastal identity.', 'assets/img/islands/ionische/korfu/korfuBild01.jpg', 'pages/islands/ionische/korfu.html', 300),
  ('island', 'kefalonia', 'Kefalonia', 'Ionische Inseln', 'Cliffs, coves and blue water', 'Kefalonia is known for dramatic beaches, caves and mountain landscapes.', 'assets/img/islands/ionische/kefalonia/kefaloniaBild01.jpg', 'pages/islands/ionische/kefalonia.html', 310),
  ('island', 'lefkada', 'Lefkada', 'Ionische Inseln', 'Dramatic beaches and bridges', 'Lefkada brings long beaches, turquoise water and easy mainland access.', NULL, 'pages/islands/ionische/lefkada.html', 320),
  ('island', 'zakynthos', 'Zakynthos', 'Ionische Inseln', 'Blue caves and shipwreck bay', 'Zakynthos mixes famous beaches, caves and a vivid summer atmosphere.', NULL, 'pages/islands/ionische/zakynthos.html', 330),
  ('island', 'ithaki', 'Ithaki', 'Ionische Inseln', 'Odysseus and quiet harbors', 'A calm island with literary weight, small villages and sheltered bays.', NULL, 'pages/islands/ionische/ithaki.html', 340),
  ('island', 'paxoi', 'Paxoi', 'Ionische Inseln', 'Tiny island, deep blue sea', 'Paxoi is a compact island set with olive trees, clear water and a slow pace.', NULL, 'pages/islands/ionische/paxoi.html', 350),
  ('island', 'kythira', 'Kythira', 'Ionische Inseln', 'Between Ionian and Aegean', 'Kythira feels remote and poetic, with waterfalls, villages and quiet shores.', NULL, 'pages/islands/ionische/kythira.html', 360),
  ('island', 'agathonissi', 'Agathonissi', 'Dodekanes', 'Small and quiet', 'A tiny island with very calm rhythms and a simple harbor life.', NULL, 'pages/islands/dodekanes/agathonissi.html', 500),
  ('island', 'astypalaia', 'Astypalaia', 'Dodekanes', 'Butterfly shaped island', 'A bright island with a castle, white houses and a strong island profile.', NULL, 'pages/islands/dodekanes/astypalaia.html', 510),
  ('island', 'chalki', 'Chalki', 'Dodekanes', 'Small harbor island', 'Chalki is compact, pastel colored and known for its peaceful waterfront.', NULL, 'pages/islands/dodekanes/chalki.html', 520),
  ('island', 'kalymnos', 'Kalymnos', 'Dodekanes', 'Cliffs and sponge divers', 'A rugged island with climbing routes, sea cliffs and a diving tradition.', NULL, 'pages/islands/dodekanes/kalymnos.html', 530),
  ('island', 'karpathos', 'Karpathos', 'Dodekanes', 'Wind, mountains and tradition', 'Karpathos combines strong local customs, mountain villages and long beaches.', NULL, 'pages/islands/dodekanes/karpathos.html', 540),
  ('island', 'kasos', 'Kasos', 'Dodekanes', 'Remote and authentic', 'Kasos is quiet, maritime and strongly shaped by its seafaring past.', NULL, 'pages/islands/dodekanes/kasos.html', 550),
  ('island', 'kastellorizo', 'Kastellorizo', 'Dodekanes', 'Colorful harbor edge', 'A very small island with a vivid harbor, steep slopes and a remote feeling.', NULL, 'pages/islands/dodekanes/kastellorizo.html', 560),
  ('island', 'kos', 'Kos', 'Dodekanes', 'Ancient sites and beaches', 'Kos mixes archaeology, bicycle-friendly streets and long coastlines.', NULL, 'pages/islands/dodekanes/kos.html', 570),
  ('island', 'leipsi', 'Leipsi', 'Dodekanes', 'Simple and sheltered', 'Leipsi offers quiet coves, a compact town and a very slow pace.', NULL, 'pages/islands/dodekanes/leipsi.html', 580),
  ('island', 'leros', 'Leros', 'Dodekanes', 'Harbors and history', 'Leros has a strong naval history, quiet bays and layered island settlements.', NULL, 'pages/islands/dodekanes/leros.html', 590),
  ('island', 'nisyros', 'Nisyros', 'Dodekanes', 'Volcano island', 'A small volcanic island with a crater landscape and a memorable center.', NULL, 'pages/islands/dodekanes/nisyros.html', 600),
  ('island', 'patmos', 'Patmos', 'Dodekanes', 'Sacred and serene', 'Patmos is known for its monastery, spiritual atmosphere and elegant lanes.', NULL, 'pages/islands/dodekanes/patmos.html', 610),
  ('island', 'rhodos', 'Rhodos', 'Dodekanes', 'Medieval town and resorts', 'Rhodos combines a famous old town, beach life and large island scale.', NULL, 'pages/islands/dodekanes/rhodos.html', 620),
  ('island', 'symi', 'Symi', 'Dodekanes', 'Elegant harbor houses', 'Symi stands out for its amphitheater harbor, pastel mansions and calm energy.', NULL, 'pages/islands/dodekanes/symi.html', 630),
  ('island', 'tilos', 'Tilos', 'Dodekanes', 'Nature and silence', 'Tilos is a quiet island with hiking terrain and a strong nature focus.', NULL, 'pages/islands/dodekanes/tilos.html', 640),
  ('island', 'chios', 'Chios', 'Nord Aegaeis', 'Mastiha and medieval villages', 'Chios combines mastiha production, villages and a varied coastline.', NULL, 'pages/islands/nordostaegaeis/chios.html', 700),
  ('island', 'ikaria', 'Ikaria', 'Nord Aegaeis', 'Slow life and hot springs', 'Ikaria is known for relaxed time, thermal waters and rugged inland scenery.', NULL, 'pages/islands/nordostaegaeis/ikaria.html', 710),
  ('island', 'lesbos', 'Lesbos', 'Nord Aegaeis', 'Wide landscapes and culture', 'Lesbos offers olive groves, ouzo traditions and a very broad island character.', NULL, 'pages/islands/nordostaegaeis/lesbos.html', 720),
  ('island', 'limnos', 'Limnos', 'Nord Aegaeis', 'Open horizons and sand', 'Limnos has broad beaches, low hills and an open windy feel.', NULL, 'pages/islands/nordostaegaeis/limnos.html', 730),
  ('island', 'samos', 'Samos', 'Nord Aegaeis', 'Green mountains and history', 'Samos blends wine, old settlements and a lush mountain profile.', NULL, 'pages/islands/nordostaegaeis/samos.html', 740),
  ('island', 'samothraki', 'Samothraki', 'Nord Aegaeis', 'Wild mountains and waterfalls', 'Samothraki is dramatic, green and famous for its rough natural terrain.', NULL, 'pages/islands/nordostaegaeis/samothraki.html', 750),
  ('island', 'thassos', 'Thassos', 'Nord Aegaeis', 'Pine forests and marble', 'Thassos combines wooded slopes, marble heritage and swim-friendly bays.', NULL, 'pages/islands/nordostaegaeis/thassos.html', 760),
  ('city', 'athens', 'Athens', 'Attica', 'Antique and present day', 'The capital connects archaeological sites with dense city life.', NULL, 'pages/cities/athens.html', 300),
  ('food', 'tzatziki', 'Tzatziki', 'Greek cuisine', 'Yogurt, cucumber, garlic', 'A classic Greek dish, fresh and cool.', NULL, 'pages/food/tzatziki.html', 400);
